// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDga3YTYU6ATyKhQ50xn8UbJ67y2XWyko',
    appId: '1:1098578252378:web:6b7e1b87c148620e193e63',
    messagingSenderId: '1098578252378',
    projectId: 'lullabook-5fea6',
    authDomain: 'lullabook-5fea6.firebaseapp.com',
    databaseURL: 'https://lullabook-5fea6-default-rtdb.firebaseio.com',
    storageBucket: 'lullabook-5fea6.firebasestorage.app',
    measurementId: 'G-QQS5T2BNPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPZVdzyADKDC2zsZpC9Ca4uDns0cMBOwM',
    appId: '1:1098578252378:android:2744d22b45f03c5b193e63',
    messagingSenderId: '1098578252378',
    projectId: 'lullabook-5fea6',
    databaseURL: 'https://lullabook-5fea6-default-rtdb.firebaseio.com',
    storageBucket: 'lullabook-5fea6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvgEJyOc-vtFenIyzMfSa95CKiciohJU',
    appId: '1:1098578252378:ios:e24403d459f8934d193e63',
    messagingSenderId: '1098578252378',
    projectId: 'lullabook-5fea6',
    databaseURL: 'https://lullabook-5fea6-default-rtdb.firebaseio.com',
    storageBucket: 'lullabook-5fea6.firebasestorage.app',
    iosBundleId: 'com.example.lullabook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvgEJyOc-vtFenIyzMfSa95CKiciohJU',
    appId: '1:1098578252378:ios:e24403d459f8934d193e63',
    messagingSenderId: '1098578252378',
    projectId: 'lullabook-5fea6',
    databaseURL: 'https://lullabook-5fea6-default-rtdb.firebaseio.com',
    storageBucket: 'lullabook-5fea6.firebasestorage.app',
    iosBundleId: 'com.example.lullabook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDga3YTYU6ATyKhQ50xn8UbJ67y2XWyko',
    appId: '1:1098578252378:web:fd82b15e9f3bbe4d193e63',
    messagingSenderId: '1098578252378',
    projectId: 'lullabook-5fea6',
    authDomain: 'lullabook-5fea6.firebaseapp.com',
    databaseURL: 'https://lullabook-5fea6-default-rtdb.firebaseio.com',
    storageBucket: 'lullabook-5fea6.firebasestorage.app',
    measurementId: 'G-BVRC42HRZG',
  );
}
